### PR TITLE
Fix incomplete help for `--unix-path`

### LINKED ISSUE #827: Incomplete docs string
https://github.com/edgedb/edgedb-cli/blob/ff5426f54805f410f6fb0be8f2d2a442106aff6f/src/options.rs#L83

In the help text for `edgedb --help-connect`:

```
        --unix-path <unix_path>
            Unix socket dir for the
```

### PR DESCRIPTION
**Pull request by tailhook**
Fixes #827

### CODE REVIEW

File: src/options.rs [hunk 1]
```diff
@@ -80,7 +80,10 @@ pub struct ConnectionOptions {
     #[clap(conflicts_with_all=&["dsn", "credentials_file", "instance"])]
     pub port: Option<u16>,
 
-    /// Unix socket dir for the
+    /// Unix socket dir or path to unix socket for the EdgeDB connection
+    ///
+    /// When dir is specified here, path to the unix socket also depends on
+    /// `--port` and `--admin` parameters.
```
Comment (1st1) [inline src/options.rs:86]:
```suggestion
    /// A path to a unix socket for the EdgeDB connection
    ///
    /// When the supplied path is a directory, the actual path will be
    /// computed using the `--port` and `--admin` parameters.
```

**Review by 1st1 — APPROVED** [review]
