### PR TITLE
Move "existing instance" error earlier

### LINKED ISSUE #396: creating an instance with already taken name
Currently, when an instance is created with a name that's already taken, the error message is printed after a table with instance summary info is printed:

```
~ » edgedb instance create foo --nightly --method=docker
┌──────────────────────┬──────────────────────────────────────────────────────────┐
│ Instance Name        │ foo                                                      │
│ Mode                 │ Docker                                                   │
│ Data Directory       │ <docker volume "edgedb_foo">                             │
│ Credentials Path     │ /home/yury/.config/edgedb/credentials/foo.json           │
│ Database Server Port │ 10700                                                    │
│ Default User         │ edgedb                                                   │
│ Default Database     │ edgedb                                                   │
│ EdgeDB Version       │ nightly_1-beta3-dev202107231400_cv202107231400 (nightly) │
└──────────────────────┴──────────────────────────────────────────────────────────┘
Initializing EdgeDB instance...
edgedb error: Credential file /home/yury/.config/edgedb/credentials/foo.json already exists. This may mean that instance is already initialized. You may run `--overwrite` to overwrite the instance.
```

This is super confusing. The command should check if the name is taken right at the beginning and should print the error message right away, not displaying the summary table at all.

In general, the table should be displayed only when the instance was successfully created.

### PR DESCRIPTION
**Pull request by tailhook**
Fixes #396

### CODE REVIEW

File: src/server/create.rs [hunk 1]
```diff
@@ -216,6 +216,14 @@ pub fn create(options: &Create) -> anyhow::Result<()> {
     let (distr, meth_name, method) = find_distribution(
         &*current_os, &avail_methods,
         &version_query, &options.method)?;
+    let credentials_path = credentials::path(&options.name)?;
+    if credentials_path.exists() && !options.overwrite {
+        anyhow::bail!("Credential file {} already exists. \
+            This may mean that instance is already initialized. \
```
Comment (1st1) [inline src/server/create.rs:222]: What else can it mean?

Comment (fantix) [reply src/server/create.rs:222]: Probably we could say "This means the instance is already initialized, or the name is taken as a link to a remote instance"?

**Review by fantix — APPROVED** [review]
Other than Yury's question, I tested this branch and it works fine.
