### PR TITLE
windows: fix when WSL1 is default and few others

### LINKED ISSUE #630: `edgedb instance create` seems to fail to select WSL 2 properly
```
Successfully installed 1.0-rc.3+147eb62
Initializing EdgeDB instance...
[edgedb] CRITICAL 4651 2022-01-12T10:37:40.845 postgres: the database system is starting up
[edgedb] WARNING 4651 2022-01-12T10:37:41.995 postgres: could not flush dirty data: Function not implemented
[edgedb] WARNING 4651 2022-01-12T10:37:42.136 postgres: could not flush dirty data: Function not implemented
[edgedb] WARNING 4627 2022-01-12T10:37:42.136 edb.server: could not flush dirty data: Function not implemented
[edgedb] CRITICAL 4669 2022-01-12T10:38:08.302 postgres: the database system is starting up
[edgedb] WARNING 4627 2022-01-12T10:38:13.885 py.warnings: /home/edgedb/.local/share/edgedb/portable/1.0-rc.3/lib/python3.10/site-packages/edb/server/server.py:1288: RuntimeWarning: coroutine '_signal_sysevent' was never awaited
[edgedb]   await binary.EdgeConnection.run_script(
[edgedb]
[edgedb] WARNING 4669 2022-01-12T10:38:14.054 postgres: could not flush dirty data: Function not implemented
edgedb error: failed to copy file from \\wsl$\EdgeDB.WSL.1\home\edgedb\.config\edgedb\credentials\foo.json to C:\Users\test\AppData\Local\EdgeDB\config\credentials\foo.json: The system cannot find the path specified. (os error 3)
```

```
> wsl --list --verbose
  NAME            STATE           VERSION
* Debian          Stopped         1
  EdgeDB.WSL.1    Stopped         1
```

### PR DESCRIPTION
**Pull request by tailhook**
Includes:
1. Silence `reset_terminal` warning (no need to reset terminal on win)
2. Parses `wsl --list` to find out version of initialized distro and
   coverts if needed (Note: there is no `wsl --status` on some systems,
   no no way to find out which version is default before registering a
   distribution; and also wslapi call returns wrong version)
3. Better newlines on wsl subprocesses (apt output was bad sometimes)
4. `DEBIAN_FRONTEND=noninteractive` for updating packages

Fixes #630

### CODE REVIEW

File: src/portable/windows.rs [hunk 1]
```diff
@@ -310,20 +352,32 @@ fn get_wsl_distro(install: bool) -> anyhow::Result<Wsl> {
...
-        echo!("Initializing WSL...");
+        echo!("Initializing WSL distribution...");
         process::Native::new("wsl import", "wsl", "wsl")
             .arg("--import")
             .arg(CURRENT_DISTRO)
             .arg(&distro_path)
             .arg(&root_path)
             .run()?;
+        let ver = get_version(CURRENT_DISTRO)?;
+        if ver != 2 {
```
Comment (elprans) [inline src/portable/windows.rs:371]: Wouldn't it be easier to run `--import` with `--version 2`?

Comment (tailhook) [reply src/portable/windows.rs:371]: Let me verify again, but I'm pretty sure my WSL cli doesn't have that option.

Comment (tailhook) [reply src/portable/windows.rs:371]: Got it after windows update.
