### PR TITLE
Don't print server backtraces when database doesn't exist

### LINKED ISSUE #1218: Don't print a server traceback on UnknownDatabaseError
We should maybe only print server tracebacks for InternalServerErrors and nothing else.
But we definitely shouldn't print it for UnknownDatabaseError

### PR DESCRIPTION
**Pull request by msullivan**
We were just always printing a stack trace for top level errors. No
reason to do that; we should only print stack traces on ISEs
typically.

Fixes #1218.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -67,7 +67,7 @@ fn main() {
                 err = arc.inner();
             }
             if let Some(e) = err.downcast_ref::<edgedb_errors::Error>() {
-                print::edgedb_error(e, true);
+                print::edgedb_error(e, false);
```
Comment (msullivan) [inline src/main.rs:70]: This is the "verbose" argument.

Also, I consider boolean arguments to functions to be an anti-pattern in languages without named arguments. We should probably make an enum for opting in to Verbose.

**Review by quinchs — APPROVED** [review]
