### PR TITLE
Fix crash in formatter

### LINKED ISSUE #125: Crash on line wrapping query responses
- EdgeDB Version: latest from git
- EdgeDB CLI Version: latest from git
- OS Version: Ubuntu 20.04

I have a very specific crasher, but it's certainly more general.

Steps to Reproduce:

1. `CREATE TYPE Note { CREATE PROPERTY  name -> str; }; CREATE TYPE Person { CREATE PROPERTY name -> str { CREATE CONSTRAINT exclusive; }; CREATE MULTI link notes -> Note; };`

2. `FOR noob in {"Phil Emarg", "Madeline Hatch"} UNION (INSERT Person {name := noob});`

3. In an 83-character wide terminal, `SELECT Person {name, notes};`. It will work if the terminal is 82 or 84 characters wide.

The crash:
```
sully> SELECT Person {name, notes};
{
  Object {name: 'Phil Emarg', notes: {}},
  Object {name: 'Madeline Hatch', notes: {}},
thread 'async-std/runtime' panicked at 'poll after end of stream', /home/sully/.cargo/git/checkouts/edgedb-rust-8bc8936b1acdc166/1dde8bc/edgedb-client/src/reader.rs:196:19
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_failed
             at src/libcore/option.rs:1264
  14: core::option::Option<T>::expect
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/option.rs:349
  15: <edgedb_client::reader::QueryResponse<D> as futures_core::stream::Stream>::poll_next
             at /home/sully/.cargo/git/checkouts/edgedb-rust-8bc8936b1acdc166/1dde8bc/edgedb-client/src/reader.rs:196
  16: <async_std::stream::stream::next::NextFuture<T> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/stream/stream/next.rs:17
  17: edgedb::print::format_rows::{{closure}}
             at src/print/mod.rs:169
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  19: edgedb::print::native_to_stdout::{{closure}}
             at src/print/mod.rs:221
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  21: edgedb::interactive::execute_query::{{closure}}
             at src/interactive.rs:385
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  23: <async_std::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/future/maybe_done.rs:71
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  25: <async_std::future::future::race::Race<L,R> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/future/future/race.rs:46
  26: edgedb::interactive::_interactive_main::{{closure}}
             at src/interactive.rs:498
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  28: edgedb::interactive::_main::{{closure}}
             at src/interactive.rs:124
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  30: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:174
  31: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:60
  32: std::thread::local::LocalKey<T>::try_with
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/local.rs:263
  33: std::thread::local::LocalKey<T>::with
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/local.rs:239
  34: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:55
  35: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:172
  36: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  37: async_task::raw::RawTask<F,R,S,T>::run
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-3.0.0/src/raw.rs:502
  38: async_task::task::Task<T>::run
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-3.0.0/src/task.rs:265
  39: smol::work_stealing::Worker::execute::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/work_stealing.rs:176
  40: scoped_tls_hkt::ScopedKey<T>::set
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  41: smol::throttle::setup
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/throttle.rs:31
  42: smol::work_stealing::Worker::execute
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/work_stealing.rs:176
  43: smol::run::run::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:151
  44: core::ops::function::FnOnce::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/ops/function.rs:232
  45: smol::context::enter
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/context.rs:8
  46: smol::run::run::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:112
  47: scoped_tls_hkt::ScopedKey<T>::set
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  48: smol::thread_local::ThreadLocalExecutor::enter
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/thread_local.rs:57
  49: smol::run::run::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:112
  50: smol::run::run::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:113
  51: smol::work_stealing::WORKER::<impl smol::work_stealing::WORKER>::set
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:264
  52: smol::work_stealing::Worker::enter
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/work_stealing.rs:149
  53: smol::run::run::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:113
  54: smol::run::run
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:115
  55: async_std::rt::RUNTIME::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/rt/mod.rs:30
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'cannot await the result of a panicked task', /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/join_handle.rs:77:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_failed
             at src/libcore/option.rs:1264
  14: core::option::Option<T>::expect
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/option.rs:349
  15: <async_std::task::join_handle::JoinHandle<T> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/join_handle.rs:77
  16: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:174
  17: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:60
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/local.rs:263
  19: std::thread::local::LocalKey<T>::with
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/local.rs:239
  20: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:55
  21: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:172
  22: smol::run::run::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:144
  23: scoped_tls_hkt::ScopedKey<T>::set
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  24: smol::throttle::setup
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/throttle.rs:31
  25: smol::run::run::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:144
  26: core::ops::function::FnOnce::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/ops/function.rs:232
  27: smol::context::enter
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/context.rs:8
  28: smol::run::run::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:112
  29: scoped_tls_hkt::ScopedKey<T>::set
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  30: smol::thread_local::ThreadLocalExecutor::enter
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/thread_local.rs:57
  31: smol::run::run::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:112
  32: smol::run::run::{{closure}}::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:113
  33: smol::work_stealing::WORKER::<impl smol::work_stealing::WORKER>::set
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:264
  34: smol::work_stealing::Worker::enter
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/work_stealing.rs:149
  35: smol::run::run::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:113
  36: smol::run::run
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.10/src/run.rs:115
  37: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:154
  38: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:60
  39: std::thread::local::LocalKey<T>::try_with
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/local.rs:263
  40: std::thread::local::LocalKey<T>::with
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/thread/local.rs:239
  41: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:55
  42: async_std::task::builder::Builder::blocking
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:154
  43: async_std::task::block_on::block_on
             at /home/sully/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/block_on.rs:33
  44: edgedb::interactive::main
             at src/interactive.rs:109
  45: edgedb::_main
             at src/main.rs:71
  46: edgedb::main
             at src/main.rs:32
  47: std::rt::lang_start::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:67
  48: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  49: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  50: std::panicking::try
             at src/libstd/panicking.rs:274
  51: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  52: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  53: std::rt::lang_start
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:67
  54: main
  55: __libc_start_main
  56: _start
```

### PR DESCRIPTION
**Pull request by tailhook**
The crash is when a last brace `}` doesn't fit screen width.

This only happened on the stream of objects printed so was not triggered
the tests before. This commit refactors tests to trigger that crash and
fixes the bug.

Fixes #125, supersedes edgedb/edgedb-rust#36

### CODE REVIEW

File: src/print/mod.rs [hunk 1]
```diff
@@ -140,6 +140,7 @@ async fn format_rows_buf<S, I, E, O>(prn: &mut Printer<'_, O>, rows: &mut S,
         // Buffer rows up to one visual line.
         // After line is reached we get Exception::DisableFlow
     }
+    *end_of_stream = true;
```
Comment (1st1) [inline src/print/mod.rs:143]: I thought the most appropriate fix would be to add an API to the stream itself to check if it was exhausted or not

Comment (tailhook) [reply src/print/mod.rs:143]: We accept any `Stream`, and `Stream` is a thing that `async_std` provides. So we can't add APIs. We can add another trait and require it, but I don't think this is needed. We also could use `StreamExt::fuse`, but that has overhead (i.e check of a flag on each iteration).

I still think that flag in code that uses stream is more appropriate (not because of the overhead, but because of the logic: we don't need to pull from the stream if everything is already buffered). Here it's a bit complicated because it goes from another function. But the purpose of that function factoring out is not encapsulation, but rather decreasing nesting and easier `return` statement. So propagating the flag like this is good enough for my taste.

Comment (1st1) [reply src/print/mod.rs:143]: Alright!
